include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-7ftX

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-us-job-fn-47e4745e-c9fc-49a3-81cb-c65173fea6f0
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-7ftX
  environment:
    name: onb-us-job-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-06T14:19:54Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-us-job-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-us-job-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-us-job-fn-47e4745e-c9fc-49a3-81cb-c65173fea6f0
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
